In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Data_consumo_Edesur_2012-2024.csv")

In [63]:
def consumo_por_agno(df, agno):
    return df[df['Año'] == agno]

def consumo_por_region(df, region):
    region = "Ede" + region
    return df[df['Empresa Distribuidora'] == region]

def consumo_por_mes(df, mes):
    return df[df['Mes'] == mes]

def consumo_por_cliente(df, cliente):
    return df[df['Tipo Cliente'] == cliente]

In [85]:
def resumen_consumo_por_region(df, region):
    df = consumo_por_region(df, region)
    
    MESES = [
    "Enero", "Febrero", "Marzo", "Abril",
    "Mayo", "Junio", "Julio", "Agosto",
    "Septiembre", "Octubre", "Noviembre", "Diciembre"
    ]

    CLIENTES = ['Ayuntamiento', 'Comercial', 'Gobierno', 'Industrial', 'Residencial']
    
    df_meses = pd.DataFrame({"Mes":[], "Energia":[], "Potencia":[]})
    
    for i in range(1, 13):
        energia = consumo_por_mes(df, i)['Energía (gwh)'].mean()
        potencia = consumo_por_mes(df, i)['Potencia (mw)'].mean()
        df_mes_temporal = pd.DataFrame({"Mes":[MESES[i-1]], "Energia":[energia], "Potencia":[potencia]})
        df_meses = pd.concat([df_meses, df_mes_temporal], ignore_index=True)
    
    df_cliente = pd.DataFrame({"Cliente":[], "Energia":[], "Potencia":[]})
    
    for cliente in CLIENTES:
        energia = consumo_por_cliente(df, cliente)['Energía (gwh)'].mean()
        potencia = consumo_por_cliente(df, cliente)['Potencia (mw)'].mean()
        df_cliente_temporal = pd.DataFrame({"Cliente":[cliente], "Energia":[energia], "Potencia":[potencia]})
        df_cliente = pd.concat([df_cliente, df_cliente_temporal], ignore_index=True)
        
    return df_meses, df_cliente

In [95]:
def resumen_consumo_por_agno(df, agno):
    df = consumo_por_agno(df, agno)
    
    REGIONES = ['Norte', "Sur", "Este"]
    df_regiones = pd.DataFrame({"region":[], "Energia":[], "Potencia":[]})
    
    for region in REGIONES:
        energia = consumo_por_region(df, region)['Energía (gwh)'].mean()
        potencia = consumo_por_region(df, region)['Potencia (mw)'].mean()
        df_region_temporal = pd.DataFrame({"region":[region], "Energia":[energia], "Potencia":[potencia]})
        df_regiones = pd.concat([df_regiones, df_region_temporal], ignore_index=True)

  
    return df_regiones

In [68]:

consumo_por_region(df, "Norte")

,Empresa Distribuidora,Tipo Cliente,Mes,Año,date,Energía (gwh),Potencia (mw)
780,EdeNorte,Ayuntamiento,1,2012,2012-01-01,5.163929,1.447920
781,EdeNorte,Ayuntamiento,1,2013,2013-01-01,5.399932,1.761840
782,EdeNorte,Ayuntamiento,1,2014,2014-01-01,5.424507,1.847024
783,EdeNorte,Ayuntamiento,1,2015,2015-01-01,5.299332,2.088257
784,EdeNorte,Ayuntamiento,1,2016,2016-01-01,5.288908,14.192144
...,...,...,...,...,...,...,...
1555,EdeNorte,Residencial,12,2020,2020-12-01,149.598710,8.132583
1556,EdeNorte,Residencial,12,2021,2021-12-01,161.462939,31.170440
1557,EdeNorte,Residencial,12,2022,2022-12-01,157.773671,32.371940
1558,EdeNorte,Residencial,12,2023,2023-12-01,175.570000,49.200000
1559,EdeNorte,Residencial,12,2024,2024-12-01,189.698934,92.975087

In [49]:
consumo_por_agno(df, 2024)

,Empresa Distribuidora,Tipo Cliente,Mes,Año,date,Energía (gwh),Potencia (mw)
12,EdeEste,Ayuntamiento,1,2024,2024-01-01,9.360000,20.950000
25,EdeEste,Ayuntamiento,2,2024,2024-02-01,8.450000,20.970000
38,EdeEste,Ayuntamiento,3,2024,2024-03-01,9.410000,20.210000
51,EdeEste,Ayuntamiento,4,2024,2024-04-01,9.120000,20.680000
64,EdeEste,Ayuntamiento,5,2024,2024-05-01,9.250000,21.010000
...,...,...,...,...,...,...,...
2287,EdeSur,Residencial,8,2024,2024-08-01,199.720000,49.630000
2300,EdeSur,Residencial,9,2024,2024-09-01,208.480000,58.710000
2313,EdeSur,Residencial,10,2024,2024-10-01,204.013046,60.281286
2326,EdeSur,Residencial,11,2024,2024-11-01,192.337804,61.745017
2339,EdeSur,Residencial,12,2024,2024-12-01,163.937036,61.068605

In [96]:
resumen_consumo_por_agno(df, 2023)

  region    Energia    Potencia
0  Norte  74.627000   99.600333
1    Sur  83.354833  148.931667
2   Este  54.699167  122.994000

In [97]:

for dataframe in resumen_consumo_por_region(df, "Norte"):
    display(dataframe)

           Mes    Energia   Potencia
0        Enero  50.636378  76.174026
1      Febrero  49.741799  75.467082
2        Marzo  49.289082  76.110320
3        Abril  52.013666  76.092427
4         Mayo  53.346771  77.162464
5        Junio  58.634325  79.336684
6        Julio  58.887059  79.440422
7       Agosto  61.136312  81.390644
8   Septiembre  61.482385  82.706095
9      Octubre  59.334611  81.437129
10   Noviembre  59.280592  81.211050
11   Diciembre  53.664419  79.260547

        Cliente     Energia    Potencia
0  Ayuntamiento    7.680515   18.012214
1     Comercial   40.300208   69.134609
2      Gobierno   19.288945   60.112989
3    Industrial   62.454838  211.553695
4   Residencial  148.378578   35.265196